# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88ae35abf369deb8db8dd69d30df4d7eda8bea5d617c2ddc908b07dd3ffb420020ac4cf5082237924979bb306ca924282acb64059c8c05c7fd9ac2119a3127a8

test:
  secret_key_base: 365f523a9ea44185de08ae04173b8b021be2484b079c03f107d709f212492b96123d12df6783162123079f3383a622b8e018f446a0107e99c1126c18931fc251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
